##############################################
#              Server settings               #
##############################################

# port
port: 1950

log_path: emotion_model_dev.log

##############################################
#              Model settings                #
##############################################

# file paths of preprocess units
preprocess:
  # cohesion probability for cohesion tokenizer
  cohesion: /scatter/workspace/pingpong/models/emotion_model_data/preprocess/tokenizer_cohesion_probability.txt
  # space model
  space_model: /scatter/workspace/pingpong/models/emotion_model_data/preprocess/space_model.model
  # typo correction
  typo_correction: /scatter/workspace/pingpong/models/emotion_model_data/preprocess/typo_correct.txt
  # system msg
  system_msg: /scatter/workspace/pingpong/models/emotion_model_data/preprocess/system_msg_list.txt

## File path specifications of each model
emoji:
  vocab: /scatter/workspace/pingpong/models/emotion_model_data/vocab.txt
  emoji_model: /scatter/workspace/pingpong/models/emotion_model_data/reaction_multitask/best_NDCG.ckpt-321728
  calibrated_classifier: /scatter/workspace/pingpong/models/emotion_model_data/20180427_calibrated_sigmoid2_multitask4.pkl
  ranking_model: /scatter/workspace/pingpong/models/emotion_model_data/20180518_reranked.xgb
  emoji2vec: /scatter/workspace/pingpong/models/emotion_model_data/emoji2vec.dict

emojiness:
  vocab: /scatter/workspace/pingpong/models/emotion_model_data/vocab.txt
  emojiness_model: /scatter/workspace/pingpong/models/emotion_model_data/emojiness/best_NDCG.ckpt-107630

sentiment:
  ranking_model: /scatter/workspace/pingpong/models/emotion_model_data/sentiment/20180710_sentiment_tagging.xgb